# Generated by Django 3.2 on 2023-05-28 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='status',
            old_name='title',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='type',
            old_name='title',
            new_name='_type',
        ),
    ]
