# Generated by Django 3.2 on 2023-05-28 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_auto_20230528_2039'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='_type',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='type',
            old_name='_type',
            new_name='type',
        ),
    ]
