# Generated by Django 3.2 on 2023-05-29 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_auto_20230528_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
    ]
